<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2012-2015 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var $this Magpleasure_Common_Block_System_Entity_Form_Element_Ajax_Dropdown_Render */
?>
<?php
if (Mage::app()->getRequest()->getControllerName() == 'catalog_product_action_attribute') {
    $attributeName = "attributes[{$this->getName()}]";
} else {
    $attributeName = $this->getName();
}
?>
<div id="<?php echo $this->getHtmlId(); ?>_container" class="mp_dropdown_container">

    <?php $values = array(); ?>
    <input value="<?php echo $this->getValue(); ?>"
           type="hidden"
           name="<?php echo $attributeName; ?>"
           id="<?php echo $this->getHtmlId(); ?>"
           style="width: 280px;"
           class="<?php echo $this->getClass(); ?>"
           <?php if ($this->getDisabled()): ?>disabled<?php endif; ?>
    />
</div>

<?php $limit = $this->getLimit(); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php if (!$this->isAjax()): ?>
    document.observe("dom:loaded", function () {
        <?php endif; ?>

        jQuery("#<?php echo $this->getHtmlId(); ?>").select2({
            placeholder: '<?php echo $this->__("Start type to select..."); ?>',
            ajax: {
                url: "<?php echo $this->getUrlPattern(); ?>",
                dataType: 'json',
                quietMillis: 100,
                data: function (term, page) {
                    return {
                        q: term,
                        l: <?php echo $limit; ?>,
                        p: page
                    };
                },
                results: function (data, page) {
                    if (data){
                        var more = (page * <?php echo $limit; ?>) < data.total;
                    }
                    return {results: data.rows, more: more};
                }
            },
            initSelection: function(element, callback) {
                return callback({
                    'id': jQuery(element).val(),
                    'text':'<?php echo $this->getResolvedValue(); ?>'
                });
            }
            <?php if ($this->getFormatSelection()): ?>
            , formatSelection: <?php echo $this->getFormatSelection(); ?>
            <?php endif; ?>
            <?php if ($this->getFormatResult()): ?>
            , formatResult: <?php echo $this->getFormatResult(); ?>
            <?php endif; ?>
            <?php if ($this->getCanUseDefaultValue() || $this->getCanUseWebsiteValue()): ?>
            , disabled: true
            <?php endif; ?>
        });

        <?php if (!$this->isAjax()): ?>
    });
    <?php endif; ?>
    //]]>
</script>
