<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

?>




<style type="text/css">

    .mp-pager .sorting {
        float: right;

    }

    .mp-pager .pages {
        float: left;
        margin: 0;
        height: 17px;
    }

    .mp-pager .sorting a.direction {
        cursor: pointer;
    }

    .mp-pager .pages li a {
        cursor: pointer;
    }

</style>

<?php $action_name = $this->getData('action_name'); ?>
<div class="pager mp-pager" ng-model="pager" ng-show="!processing && pager.total_count>0">

    <div class="sorting" ng-show="pager.can_sort">
        <label><?php echo $this->__('Sort By:') ?></label>
        <select ng-model="pager.sort_position" ng-change="<?php echo $action_name ?>(pager.current_page)"
                ng-options="key for (key, value) in pager.sort_list"></select>
        <a class="direction" ng-model="pager.direction_position"
           ng-click="pager.direction_position=[1, 0][pager.direction_position];  <?php echo $action_name ?>(pager.current_page);"
           title="{{pager.direction_title[pager.direction_position]}}">
            <img ng-src="<?php echo $this->getSkinUrl('images/') ?>{{pager.direction_src[pager.direction_position]}}"
                 alt="{{pager.direction_title[pager.direction_position]}}" class="v-middle"/>
        </a>
    </div>

    <div class="pages" ng-show="pager.last_page_num > 1">
        <ol>
            <li ng-show="pager.current_page!=1">
                <a class="previous"
                   ng-click="<?php echo $action_name ?>(1)"
                   title="<?php echo $this->__('Previous') ?>">
                    <?php echo $this->__('Prev'); ?>
                </a>
            </li>

            <li ng-show="pager.jump > 1 && pager.frame_start < 1 ">
                <a ng-click="<?php echo $action_name ?>(pager.prev_jump_page);" class="first">1</a>
            </li>

            <li ng-show="pager.prev_jump_page !== null">
                <a class="previous_jump" ng-click="<?php echo $action_name ?>(pager.prev_jump_page);">...</a>
            </li>

            <li ng-repeat="item in pager.pages">
                <span ng-if="item==pager.current_page">{{item}}</span>
                <a ng-if="item!=pager.current_page" ng-click="<?php echo $action_name ?>(item);">{{item}}</a>
            <li>

            <li ng-show="pager.next_jump_page !== null">
                <a class="next_jump" ng-click="<?php echo $action_name ?>(pager.next_jump_page);">...</a>
            </li>

            <li ng-show="pager.jump > 1 && pager.frame_end < pager.last_page_num">
                <a class="last" ng-click="<?php echo $action_name ?>(pager.last_page_num)">
                    {{pager.last_page_num}}
                </a>
            </li>

            <li ng-show="pager.current_page < pager.last_page_num">
                <a class="next" ng-click="<?php echo $action_name ?>(pager.next_page)"
                   title="<?php echo $this->__('Next') ?>">
                    <?php echo $this->__('Next'); ?>
                </a>
            </li>

        </ol>

    </div>
</div>
