<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var $this Magpleasure_Common_Block_Template */
?>

<?php $_uid=$this->getData('uid'); ?>
<div id="mp_dialogs_<?php echo $_uid; ?>" class="mp-dialogs-container" ng-show="true"
     align="center">
    <div id="mp_modal_overlay" class="overlay_magento mp-overlay_modal"></div>
    <div id="dialog_contents_<?php echo $_uid; ?>" class="mp-dialog_contents" align="left">
        <?php echo $this->getChildHtml('magpleasure.dialogs.content.' . $_uid); ?>
    </div>
</div>


<script type="text/javascript">
    //<![CDATA[

    function verticalCenterDialog(name) {
        var contents = $('dialog_contents_' + name);
        var dialogs = $("mp_dialogs_" + name);

        if (contents && dialogs.style.display == 'block') {
            var block_height = contents.clientHeight;
            var h = document.body.clientHeight;
            var block_top = (h - block_height) / 2;
            if (block_top < 0)
                block_top = 0;
            contents.style.top = block_top + 'px';
        }
    }

    if (window.addEventListener) {
        window.addEventListener('resize', function () {
            verticalCenterDialog('<?php echo $_uid; ?>');
        });
    } else {
        window.attachEvent('onResize', function () {
            verticalCenterDialog('<?php echo $_uid; ?>');
        });
    }

    $('mp_dialogs_<?php echo $_uid; ?>').onmousewheel  =
        function(event) {
            if (event && event.toElement.localName=='textarea'){
                /*to do disable position*/
            }else{
                event.preventDefault();
            }
        };

    // ]]>
</script>