<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

?>

<form id="mp_<?php echo $this->getData('uid'); ?>"  novalidate
    name="<?php echo $this->getData('uid'); ?>"
    <?php if ($this->getFormController()): ?> ng-controller="<?php echo $this->getFormController(); ?>" <?php endif; ?>>
    <div class="mp-modal-header dialog-header">
        <h3><?php echo $this->getTitle(); ?></h3>
        <button id="close_buton_<?php echo $this->getData('uid'); ?>" type="button" class="mp-close"
            <?php if ($this->getFormController()): ?> ng-click="closeDialog()" <?php endif; ?>>×
        </button>
    </div>
    <div class="form-add mp-content-form">
        <div class="hor-scroll">
            <?php echo $this->getChildHtml($this->getData('content')); ?>
        </div>
    </div>
    <div class="mp-modal-footer  a-center">
        <?php echo $this->getChildHtml($this->getData('footer')); ?>
        <span><?php echo $this->__(' or '); ?>
            <a <?php if ($this->getFormController()): ?> ng-click="closeDialog()" <?php endif; ?>
                style="cursor: pointer;">
                <?php echo $this->__('Close'); ?>
            </a>
        </span>
    </div>
</form>

