<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

?>

<div class="mp-dialog-overlay" id="mp-dialog-overlay" style="display: none;"></div>
<div class="mp-dialog-loader" id="mp-dialog-loader" style="display: none;">
    <div class="mp-dialog-loader-wrapper">
        <div class="mp-dialog-loader-container">
            <div class="ajax-loager"></div>
            <div class="loader-message"><span><?php echo $this->__("Loading..."); ?></span></div>
        </div>
    </div>
</div>