<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2012-2015 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var $this Magpleasure_Common_Block_System_Entity_Form_Element_Wysiwyg_Render */
?>
<?php
if (Mage::app()->getRequest()->getControllerName() == 'catalog_product_action_attribute') {
    $attributeName = "attributes[{$this->getName()}]";
} else {
    $attributeName = $this->getName();
}
?>

<textarea
    name="<?php echo $attributeName; ?>"
    id="<?php echo $this->getHtmlId(); ?>"
    title="<?php echo $this->getTitle(); ?>"
    ><?php echo $this->getEscapedValue(); ?></textarea>

<script type="text/javascript">


    //<![CDATA[
    wysiwyg<?php echo $this->getHtmlId(); ?> = new mpTinyMceWysiwygSetup("<?php echo $this->getHtmlId(); ?>", <?php echo $this->getSetupConfigJson());
    Event.observe(window, "load", wysiwyg<?php echo $this->getHtmlId(); ?>.setup.bind(wysiwyg<?php echo $this->getHtmlId(); ?>, "exact");
    editorFormValidationHandler = wysiwyg<?php echo $this->getHtmlId(); ?>.onFormValidation.bind(wysiwyg<?php echo $this->getHtmlId(); ?>);

    //    varienGlobalEvents.attachEventHandler("formSubmit", editorFormValidationHandler);
    varienGlobalEvents.attachEventHandler("tinymceBeforeSetContent", wysiwy<?php echo $this->getHtmlId(); ?>.beforeSetContent.bind(wysiwyg<?php echo $this->getHtmlId(); ?>));
    varienGlobalEvents.attachEventHandler("tinymceSaveContent", wysiwyg<?php echo $this->getHtmlId(); ?>.saveContent.bind(wysiwyg<?php echo $this->getHtmlId(); ?>));
    //]]>


    document.observe('dom:loaded', function () {

        tinyMCE.settings = {
            width: '600px',
            height: '300px',
            menubar: false,
            toolbar_items_size: 'small',
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste template"
            ],
            toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link code ",
            templates: [
                {title: 'My Template 1', content: 'Test 1'},
                {title: 'My Template 2', content: 'Test 2'}
            ]
        };

        tinyMCE.execCommand('mceAddEditor', true, '<?php echo $this->getHtmlId(); ?>');
    });

</script>