<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    master
 * @copyright  Copyright (c) 2012-2015 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<script type="text/javascript">
    document.observe('dom:loaded', function(){
        var lightbox = new Lightbox({
            fileLoadingImage: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."magpleasure/libs/lightbox/images/loading.gif"; ?>',
            fileBottomNavCloseImage: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."magpleasure/libs/lightbox/images/close.gif"; ?>'
        });
    });
</script>
